### PR TITLE
feat(ui): visual + layout improvements

### PR DESCRIPTION
**Pull request by rbreeze**
- Moves tabs to upper left hand corner, and collapses tab titles to tooltips
- Moves settings dropdown to right hand side of Project name
- Refreshed Freight timeline appearance
- Use consistent Tailwind colors across the interface

Before:
Screenshot 2024-07-23 at 16 55 17

After:
Screenshot 2024-07-23 at 16 57 35

### CODE REVIEW

**Comment by krancour** [comment]
@rbreeze do you happen to have a "before" screen shot to compare this to. Or a few bullet points would be fine, too.

I took this for a test drive and it works well and I did compare it side by side with v0.8.0, but I'm not sure that the examples I used gave me a comprehensive understanding of everything that changed.

**Comment by rbreeze** [comment]
@krancour sure thing! Updated the primary PR description

**Comment by krancour** [comment]
@rbreeze I can spot all the layout differences easily. Is there anything significant that changed besides that?

**Comment by rbreeze** [comment]
@krancour No, no functional changes... the large blocks showing up in the diff are primarily from reorganizing a couple of components to allow for the redesign, so they're mostly just indentation changes.

**Review by krancour — APPROVED** [review]

**Pull request merged**
