### PR TITLE
feat: add security context field to helm charts

### PR DESCRIPTION
**Pull request by michaelasper**
Expose security context field to helm charts

Issue: https://github.com/akuity/kargo/issues/1661

### CODE REVIEW

**Comment by rdelpret** [comment]
LGTM!

**Review by krancour — APPROVED** [review]

**Comment by krancour** [comment]
Apologies. Approved the wrong PR accidentally. This hasn't been reviewed yet.

**Review by hiddeco — APPROVED** [review]
Thanks for your contribution! 🍰 

We will have to wait a little bit until the v0.5.0 release branch gets cut to allow this to go in. But the PR itself looks good to me!

**Comment by krancour** [comment]
We're not _quite_ as close to cutting v0.5.0 as we thought we were, so I'll move this into v0.5.0 since it's ready to go and this now won't feel like a last minute thing that we squeezed in.

**Comment by michaelasper** [comment]
I'll resolve the conflicts tomorrow, thanks for getting to these!

**Comment by krancour** [comment]
@michaelasper thanks! If you can't get to them, just let me know. I don't mind handling.

**Comment by michaelasper** [comment]
@krancour should be good to go!

**Comment by krancour** [comment]
Thank you @michaelasper!

**Pull request merged**
