### PR TITLE
feat: use event handlers to re-reconcile related objects

### PR DESCRIPTION
**Pull request by jessesuen**
Partially resolves https://github.com/akuity/kargo/issues/699

This PR does a few things:

1. The stage reconciler watches promos that enter into a terminal state. Then it enqueues the owning Stage
2. The stage reconciler watches all stages whose history has changed. Then it enqueues downstream Stages
3. Fixes a bug in the logger used in the AppHealthSyncStatusChangePredicate

Using the above technique, we can make Stage reconciliation reactive enough that https://github.com/akuity/kargo/issues/699 becomes less noticeable, but still possible.

### CODE REVIEW

**Comment by jessesuen** [comment]
I think it may be possible to completely remove the App reconciler, if we use the same technique that I did here where the Stage watches Promotion objects (as a separate effort).

**Comment by krancour** [comment]
I understand parts 2 and 3.

I am confused by part 1 and why the stages reconciler would also be watching promos now...

Wouldn't it be simpler to have the promos reconciler enqueue the owning stage for reconciliation when it completes a promotion?

**Comment by jessesuen** [comment]
@krancour I don't think the Kubebuilder approach will work:

1. It doesn't appear there is a way where I can only enqueue the Stage only if the Promo goes from non-terminal to terminal. e.g. there is no Update() mechanism to compare two objects to see if it changed state in the way that I care about.
2. What we have today, only to builds an efficient index on listing non-terminal promos by stage, to make the reconcile slightly faster, but it doesn't have a mechanism to requeue Stages.
3. The Kubebuilder technique relies on a cruder `Owns` helper to reconcile the Cronjob, but it does so on _**any**_ update, but we only care when a promotion is finished. If you see the docs, it is only doing the first half of what I want:

```
// Owns defines types of Objects being *generated* by the ControllerManagedBy, and configures the ControllerManagedBy to respond to
// create / delete / update events by *reconciling the owner object*.  This is the equivalent of calling
// Watches(&source.Kind{Type: <ForType-forInput>}, &handler.EnqueueRequestForOwner{OwnerType: apiType, IsController: true}).
func (blder *Builder) Owns(object client.Object, opts ...OwnsOption) *Builder {
``` 

So I think the approach I am taking is valid. Here is the example I followed:

https://github.com/kubernetes-sigs/controller-runtime/blob/main/examples/builtins/main.go#L67-L72

**Comment by krancour** [comment]
> I don't think the Kubebuilder approach will work

Yep. I see now that `.Owns()` doesn't really offer a way to limit the Promo changes that you want to trigger a Stage reconciliation.

What you're doing here makes sense and agrees with the docs. 👍 

LGTM

**Review by krancour — APPROVED** [review]

**Pull request merged**
