### PR TITLE
feat(ui): Warehouse creation form

### LINKED ISSUE #1538: Warehouse creation wizard
Current the UI has no feature for creating a new Warehouse.

@jessesuen, "wizard" was your wording. Could we guess that initially, this isn't more than was done for creating Stages? i.e. Pop open a YAML editor with example YAML and schema-aware context help?

### PR DESCRIPTION
**Pull request by rpelczar**
Fixes #1538

image

image

### CODE REVIEW

**Comment by hiddeco** [comment]
Would it be an idea to provide a visual indicator to show the button is actually a dropdown? Classic bootstrap example: https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropdowns

**Comment by krancour** [comment]
@rpelczar the modal itself works great!

Thing I am noticing now is some trouble with a bug I've noticed before and keep forgetting to report...

A warehouse are never displayed in the DAG unless there is a Stage subscribed to it.

So creating a new Warehouse works, but with nothing initially subscribed to it, it doesn't show up in the view, which I think is likely to lead people to believe the modal didn't do its job.

**Comment by rbreeze** [comment]
@krancour I see why this bug happens, IMO we should merge this PR and I'll open a fast-follow fix for that bug

**Review by rbreeze — APPROVED** [review]

**Comment by krancour** [comment]
@rbreeze that sgtm.

**Review by krancour — APPROVED** [review]

**Comment by krancour** [comment]
@rpelczar hope you don't mind that I merged this on your behalf. I wanted to make sure this was included in a v0.5.0-rc.1.

**Comment by rbreeze** [comment]
@krancour Here's the fix: https://github.com/akuity/kargo/pull/1689

**Pull request merged**
