### PR TITLE
feat(controller,api): adds a cabundle option to the values.yaml file.

### PR DESCRIPTION
**Pull request by lknite**
If enabled, it adds an initContainer to the api/controller deployment which mounts certs provided via either a configMap or secret.

Uses an emptyDir, or optionally a pvc, for the actual certs mount within the controller; this allows the controller to write to the certs folder if needed.

### CODE REVIEW

**Comment by krancour** [comment]
What is the point of the init container and the volumes here? I'm not clear about what would be insufficient about _just_ mounting a user-provided secret into the container that contains the trust store.

**Comment by krancour** [comment]
Following up on my previous comment:

The original issue was #2271 and it seemed to be about CA for the OIDC IDP, so in the back of my mind, that was the context/scope. _That_ issue can be solved by adding more CA certs directly to the http client that the Kargo _API server_ uses to communicate with the IDP and that doesn't require anything more than those certs to be mounted somewhere where the API server will look for them. e.g. Secrets do the trick. No init container needed. Very small code change needed.

This PR seems to address the issue of custom CA certs more-broadly, at the system level, which is nice, but also seems to do it for the _controller_ and not the API server, meaning it doesn't solve the original issue.

Perhaps what is required here is some clarification on the scope of what you are trying to solve for.

**Comment by krancour** [comment]
@lknite, ok I get where you were going. It was the scope / area where you implemented the change that confused me a bit. With greater clarity on that now, I will take another look.

**Comment by lknite** [comment]
added to kargo-api as well, now will resolve issue https://github.com/akuity/kargo/issues/2271

**Comment by lknite** [comment]
tried to update other files on my fork, i might have broken things will fork again and redo my changes

**Comment by lknite** [comment]
tried to update my fork, might have messed up things will redo with a new pull request

**Pull request closed without merging**
