### PR TITLE
feat: add annotations to workload resources

### PR DESCRIPTION
**Pull request by michaelasper**
Allow annotations on kubernetes workload resources

Issue: https://github.com/akuity/kargo/issues/1663

### CODE REVIEW

**Comment by krancour** [comment]
Hi @michaelasper thanks for the contribution!

We're pushing really hard to wrap up v0.5.0 right now, so I'm going to add this to the v0.6.0 milestone and we'll get to reviewing this in earnest probably next week.

**Review by hiddeco — APPROVED** [review]
As with the other PR, we are still working on cutting the v0.5.0 release branch. But besides this, it looks good to me. Thanks! 🙇

**Comment by hiddeco** [comment]
Ah, one thing. You need to run `make hack-codegen` to regenerate the documentation for the values (same for the other PR).

**Comment by michaelasper** [comment]
> Ah, one thing. You need to run `make hack-codegen` to regenerate the documentation for the values (same for the other PR).

Sorry for missing this, added it to both PRs!

**Comment by krancour** [comment]
We're not _quite_ as close to cutting v0.5.0 as we thought we were, so I'll move this into v0.5.0 since it's ready to go.

Thank you @michaelasper!

**Pull request merged**
