### PR TITLE
fix(auth): token renew failure

### PR DESCRIPTION
**Pull request by Marvin9**
Not sure if this was issue previously or after recent library major version bump but token renew failures went unnoticed and causing page stuck on loading spinner

### CODE REVIEW

**Comment by krancour** [comment]
I ran into this also starting just recently.

**Review by krancour — APPROVED** [review]

**Comment by krancour** [comment]
Thank you for being right on top of this!

**Comment by krancour** [comment]
Womp womp.

**Comment by Marvin9** [comment]
@krancour this might not necessarily needs to be backported due to the reason that this _might_ be caused by recent major version bump of oauth dependency https://github.com/akuity/kargo/pull/3039, which hasn't been released. I will confirm

**Pull request merged**
