### PR TITLE
Issue/864

### PR DESCRIPTION
**Pull request by maksimstankevic**
Hey! I'd like to contribute to kargo and this is my first PR, meant for https://github.com/akuity/kargo/issues/864

### CODE REVIEW

**Review by gdsoumya — CHANGES_REQUESTED** [review]
The current approach is done on the client side, which is acceptable but imo as more efficient solution we should implement this on the server.

**Comment by krancour** [comment]
@gdsoumya, fyi, this seems to be a problem in general... I opened #1098 over this.

**Comment by krancour** [comment]
This has the potential to clash with #1102/#1148, which I noted [here](https://github.com/akuity/kargo/issues/864#issuecomment-1739184919) was a possibility.

That clash is resolvable through the right permissions (permission to list Kargo resources across all namespaces), but I am trying to wrap my head around how likely/frequently that will be given out.

Ultimately, I am curious if we're doing this because there's a demonstrable need for it or just because `kubectl` has `-A`, so we feel the need for something equivalent. Put another way, how often do we suppose someone will _want_ to see Stages, Freight, or Promotions across projects? What sort of workflow does that support when most everything one does in Kargo is scoped to the project-level?

@christianh814 let's chat offline about this?

@maksimstankevic I'm also interested in hearing your perspective. Is this PR purely altruistic (thank you!) or do you have a personal need for this feature? I think hearing the perspective of an actual user will help to make a more informed decision about this.

**Comment by maksimstankevic** [comment]
I'm closing this PR as it looks like now  https://github.com/akuity/kargo/issues/1098 is standing in the way and it's not clear "--all-projects" option for get commands will live.

**Comment by krancour** [comment]
The clash is actually with #1148

Just to put some closure on this for anyone following...

#864 was opened more from a parity-with-kubectl perspective and not out of a demonstrated need for the feature. If it weren't for the clash with #1148, that would have been fine, _but_ reconciling these two things isn't worth the effort until there's a demonstrated need for #864.

If that need ever arises, this will be re-opened.

Thanks for the effort that went into this @maksimstankevic.

**Pull request closed without merging**
