### PR TITLE
fix(ui): infinite reload when navigating to nonexistent project

### LINKED ISSUE #2527: UI appears distorted when the project does not exist
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

If you delete the project and refresh the UI for the deleted project path, the UI will appear distorted.

# Screenshots

image

# Steps to Reproduce

Go to the `/project/unknown-project` endpoint of the kargo and you'll see the UI a bit distorted.

# Version

```
Client Version: v0.8.7
Server Version: v0.8.7
```

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #2527

### CODE REVIEW

**Review by krancour — APPROVED** [review]

**Review by Marvin9 — CHANGES_REQUESTED** [review]
This still let the child components to make queries as if project does not exists. I will make changes

**Review by Marvin9 — APPROVED** [review]
@rpelczar @krancour want to take a quick look?

**Comment by rpelczar** [comment]
> @rpelczar @krancour want to take a quick look?

I already took a look, but I want to try something different.

**Comment by Marvin9** [comment]
> I already took a look, but I want to try something different.

Let me know if you want to try in this PR. If not, I can merge it.

**Pull request merged**
