### PR TITLE
fix(ui): use YAML response option for AnalysisRun

### PR DESCRIPTION
**Pull request by hiddeco**
Part of: #1785

### CODE REVIEW

**Comment by hiddeco** [comment]
The other ones appear to be building their "view" from the list endpoints, not the get endpoints...

**Comment by krancour** [comment]
> The other ones appear to be building their "view" from the list endpoints, not the get endpoints...

That seems odd. Do we know why we're not using get for those?

@rpelczar or @rbreeze?

**Comment by hiddeco** [comment]
The reason I think, is that to display an overview of things we already list the objects. Which means that it's "cheaper" to pass the data from the list response to the modal.

For AnalysisRuns however, the list is built up from reference data from the Stage. Which means we need to get the further data to display the modal.

**Comment by krancour** [comment]
> The reason I think, is that to display an overview of things we already list the objects. Which means that it's "cheaper" to pass the data from the list response to the modal.

I don't mind the minor expense if it buys us more up-to-date data and cleaner YAML.

**Comment by hiddeco** [comment]
I don't mind either, but I fear it's beyond my Typescript skill level to make that happen quickly and/or in a neat way 😅

**Review by rpelczar — APPROVED** [review]

**Comment by krancour** [comment]
> I fear it's beyond my Typescript skill level to make that happen quickly and/or in a neat way

You and me both, @hiddeco.

Just open a follow-up and let's merge this.

**Pull request merged**
