### PR TITLE
feat(ui): Add freightline

### PR DESCRIPTION
**Pull request by rbreeze**
Color selection is done deterministically by taking all Stages and mapping them to a unique color. Additionally, this PR begins supporting the annotation `kargo.akuity.io/color` for custom color selection.

CleanShot 2023-09-08 at 01 01 23@2x

CleanShot 2023-09-08 at 01 01 17@2x

### CODE REVIEW

**Review by jessesuen — APPROVED** [review]
Rubber stamp approval based on deploying it and trying it out.

**Comment by jessesuen** [comment]
Some feedback, can be addressed now or later:
1. If we don't have 10 freight, then don't show extra boxes
2. We shouldn't limit it to 10. Maybe base it on width of browser
3. The "Stages" title feels out of place. Maybe it should be moved under freightline

image

**Comment by jessesuen** [comment]
I noticed the order of the freight keeps flapping. Do you know why?

https://github.com/akuity/kargo/assets/12677113/c1cd29a1-c772-4449-a97f-424665911515

**Comment by rbreeze** [comment]
@jessesuen  I think the flapping was happening because I had not sorted by first seen timestamp. I just pushed some changes that included sorting.

I also improved the layout:

CleanShot 2023-09-08 at 12 10 05@2x

**Comment by rbreeze** [comment]
Most recent update: CleanShot 2023-09-08 at 23 26 00@2x

**Comment by rbreeze** [comment]
Added pinning feature,
CleanShot 2023-09-08 at 23 49 59@2x

and links to Git commits:
CleanShot 2023-09-08 at 23 49 24@2x

**Pull request merged**
