### PR TITLE
feat: custom PR title (#3063)

### LINKED ISSUE #3063: Custom PR Title
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

It would be really great if we could set a custom PR title via the git-open-pr step.  Either completely override the last commit massage or, if possible, Add to the title.  

# Motivation

As suggested https://github.com/akuity/kargo/issues/3002
I can absolutely forsee someone wanting the ability to customize the title and thus overriding the last commit message

I know a lot of shops will add things like [staging] or [release] at the beginning of the title which might trigger automated workflows as an example.

# Suggested Implementation

### PR DESCRIPTION
**Pull request by muenchdo**
closes #3063

### CODE REVIEW

**Comment by muenchdo** [comment]
@krancour Please let me know your thoughts on testing here. My thinking here is that we can both assume expressions in promotion steps are evaluated properly (likely tested elsewhere), and that if I pass any title to a Git provider's `CreatePullRequest`, the pull request will be created with the given title.

**Comment by krancour** [comment]
@muenchdo correct on both counts. 😄

**Comment by krancour** [comment]
@muenchdo I think if you re-run codegen, this looks g2g.

**Review by krancour — APPROVED** [review]
LGTM

Thanks for this @muenchdo!

**Pull request merged**
