### PR TITLE
feat(ui): ability to collapse old freight in freightline

### PR DESCRIPTION
**Pull request by rbreeze**
In many cases, Freightline are full of dozens or hundreds of old, unused freight that slows down the UI. This PR adds a toggle to hide all freight older than the oldest freight currently in use.

Screenshot 2024-06-24 at 10 48 32
Screenshot 2024-06-24 at 10 48 22

### CODE REVIEW

**Comment by krancour** [comment]
This is super useful!

**Comment by krancour** [comment]
@rbreeze what is the behavior when _no_ Freight are currently in use? i.e. New Project?

**Comment by rbreeze** [comment]
@krancour In this case, the button would have no effect (it wouldn't hide any freight)... so given that, I think it's best to hide the button when no freight are in use. I'll go ahead and add that behavior

**Review by krancour — APPROVED** [review]
Test drove and this is 🔥

**Pull request merged**
